/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanpedrog
 */
public class addViaticoVehiculo extends javax.swing.JDialog {
    Conexion cbd=new Conexion();
    Connection cn=cbd.getConexion();
    int idSolicitudVehiculo=-1;
    String idSolicitud;//Guarda el id de la solicitud
    String fecha;//Guarda la fecha que viene de la otra pantalla
    /**
     * Creates new form addViaticoVehiculo
     */
    public addViaticoVehiculo() {
        initComponents();
    }
    public addViaticoVehiculo(java.awt.Frame parent,boolean modal,String idSolicitud,String fecha){
        super(parent,modal);
        initComponents();
        this.idSolicitud=idSolicitud;
        this.fecha=fecha;
        refrescarPantalla(idSolicitud,fecha);
    }
    public void refrescarPantalla(String idSolicitud,String fecha){
        idSolicitudVehiculo=Integer.parseInt(idSolicitud);
        try{
            //Obtenemos todos los empleados que están asociados a esta solicitud de vehiculo
            ResultSet res=cbd.getTabla("select * from vehiculo_viatico where solicitud_vehiculo_idsolicitud_vehiculo="+idSolicitud+";", cn); 
            List<String> empleadosAsignados=new ArrayList<String>();
            while(res.next()){
                empleadosAsignados.add(res.getString("solicitud_viatico_idSolicitud"));
            }
            llenarTabla(empleadosAsignados);
            //--------------------------------
            //Obtenemos las solicitudes de empleados que no hayan sido aceptadas a partir de la fecha de la solicitud de vehiculo
            res=cbd.getTabla("select * from solicitud_viatico where estado='A' and fecha_salida>='"+fecha+"';", cn);
            List<String> empleadosDisponibles=new ArrayList<String>();
            while(res.next()){
                boolean disponible=true;
                //Recorremos a los empleados no disponibles para no mostrarlos
                for(int i=0;i<empleadosAsignados.size();i++){
                    if(empleadosAsignados.get(i).equals(res.getString("idSolicitud"))){
                        disponible=false;//Si encontramos a uno de los empleados ya asignados, no lo ponemos disponible
                    }
                }
                if(disponible){
                    empleadosDisponibles.add(res.getString("idSolicitud")+"-"+res.getString("nombre"));
                }
            }
            //Llenamos el combo box de los empleados disponibles para asignar un vehiculo
            llenarComboBoxEmpleados(empleadosDisponibles);
        }catch(SQLException e){}
    }
    private void llenarComboBoxEmpleados(List<String> empleados){
        cmbEmpleados.removeAllItems();
        cmbEmpleados.addItem("Seleccione empleado");
        for(int i=0;i<empleados.size();i++){
            cmbEmpleados.addItem(empleados.get(i));
        }
    }
    public void llenarTabla(List<String>empleados)throws SQLException{
        //Llenamos la tabla con los empleados que ya han sido asignados a la solicitud de vehiculo
        //Aplicamos el formato al modelo de la tabla
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Nombre");
        //Agregamos el nombre de la persona que hizo la solicitud del vehiculo
        ResultSet res=cbd.getTabla("select nombre from solicitud_vehiculo where idSolicitud_Vehiculo="+idSolicitudVehiculo, cn);
        while(res.next()){
            model.addRow(new Object[]{res.getString("nombre")});
        }
        //sacamos los nombres de los empleados asignados.
        if(empleados.size()>0){
            String query="select nombre from solicitud_viatico where idSolicitud="+empleados.get(0);
            for(int i=1;i<empleados.size();i++){
                query+=" or idSolicitud="+empleados.get(i);
            }
            res=cbd.getTabla(query, cn);
            while(res.next()){
                model.addRow(new Object[]{res.getString("nombre")});
            }
        }
        tabla.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbEmpleados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnListo = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, 228, -1));

        jLabel1.setText("Seleccione el id de la solicitud de viático y el empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 65, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 140, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 12, -1, 344));

        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        getContentPane().add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 170, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formularios.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 897, 369));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(cmbEmpleados.getSelectedIndex()!=0){
            String item=cmbEmpleados.getSelectedItem()+"";
            String idSolicitud=item.split("-")[0];
            cbd.ejecutar("INSERT INTO vehiculo_viatico values("+idSolicitudVehiculo+","+idSolicitud+");");
            refrescarPantalla(this.idSolicitud,this.fecha);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addViaticoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addViaticoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addViaticoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addViaticoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addViaticoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnListo;
    private javax.swing.JComboBox<String> cmbEmpleados;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
