/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Conexion;
import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author guillermo
 */
public class visSolicitudPase extends javax.swing.JDialog {
    
    Conexion cbd = new Conexion();
    Connection cn = cbd.getConexion();
    
    String folio1="";
    String nombre1="";
    String puesto1="";
    String area1="";
    String fecha1="";
    String horaes1="";
    String horall1="";
    String horas1="";
    String tipohorario1="";
    String tipoasunto1="";
    String asunto1="";
    String estado1="";

    /**
     * Creates new form visSolicitudPase
     */
    public visSolicitudPase(java.awt.Frame parent, boolean modal,String fol) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Consulta de información del folio \""+fol+"\"");
    }

    public visSolicitudPase() {
        initComponents();
        
    }

    private visSolicitudPase(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_vissolipase = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtarea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txthoraes = new javax.swing.JTextField();
        lblAviso = new javax.swing.JLabel();
        txtpuesto = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtasunto = new javax.swing.JTextArea();
        txtfolio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthorall = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthoras = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttipohorario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttipoasunto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pn_vissolipase.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pn_vissolipase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        pn_vissolipase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 43, -1, -1));

        txtnombre.setEditable(false);
        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombreFocusLost(evt);
            }
        });
        pn_vissolipase.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 38, 215, -1));

        txtarea.setEditable(false);
        txtarea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pn_vissolipase.add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 69, 215, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Area:");
        pn_vissolipase.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Asunto:");
        pn_vissolipase.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Puesto:");
        pn_vissolipase.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 104, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha:");
        pn_vissolipase.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 135, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hora E/S:");
        pn_vissolipase.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 170, -1, -1));

        txthoraes.setEditable(false);
        txthoraes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txthoraes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraesActionPerformed(evt);
            }
        });
        pn_vissolipase.add(txthoraes, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 162, 215, -1));

        lblAviso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pn_vissolipase.add(lblAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 225, 15, -1));

        txtpuesto.setEditable(false);
        pn_vissolipase.add(txtpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 100, 215, -1));

        txtfecha.setEditable(false);
        pn_vissolipase.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 131, 215, -1));

        txtasunto.setEditable(false);
        txtasunto.setColumns(20);
        txtasunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtasunto.setRows(5);
        jScrollPane2.setViewportView(txtasunto);

        pn_vissolipase.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 358, 110));

        txtfolio.setEditable(false);
        txtfolio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfolio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfolioFocusLost(evt);
            }
        });
        txtfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfolioActionPerformed(evt);
            }
        });
        pn_vissolipase.add(txtfolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 7, 215, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Folio:");
        pn_vissolipase.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 12, -1, -1));

        txthorall.setEditable(false);
        txthorall.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txthorall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorallActionPerformed(evt);
            }
        });
        pn_vissolipase.add(txthorall, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 191, 215, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Hora de llegada:");
        pn_vissolipase.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 195, -1, -1));

        txthoras.setEditable(false);
        txthoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txthoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorasActionPerformed(evt);
            }
        });
        pn_vissolipase.add(txthoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 220, 215, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Horas:");
        pn_vissolipase.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 225, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tipo de horario:");
        pn_vissolipase.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        txttipohorario.setEditable(false);
        txttipohorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttipohorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipohorarioActionPerformed(evt);
            }
        });
        pn_vissolipase.add(txttipohorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 6, 215, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tipo de asunto:");
        pn_vissolipase.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        txttipoasunto.setEditable(false);
        txttipoasunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttipoasunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoasuntoActionPerformed(evt);
            }
        });
        pn_vissolipase.add(txttipoasunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 37, 215, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Estado:");
        pn_vissolipase.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 205, -1, -1));

        txtestado.setEditable(false);
        txtestado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        pn_vissolipase.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 200, 215, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formularios.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(861, 265));
        pn_vissolipase.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_vissolipase, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_vissolipase, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreFocusLost

    private void txthoraesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraesActionPerformed

    private void txtfolioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfolioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfolioFocusLost

    private void txthorallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorallActionPerformed

    private void txthorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasActionPerformed

    private void txttipohorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipohorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipohorarioActionPerformed

    private void txttipoasuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoasuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoasuntoActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfolioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txtfolio.setText(folio1);
        txtnombre.setText(nombre1);
        txtpuesto.setText(puesto1);
        txtarea.setText(area1);
        txtfecha.setText(fecha1);
        txthoraes.setText(horaes1);
        txthorall.setText(horall1);
        txthoras.setText(horas1);
        txttipohorario.setText(tipohorario1);
        txttipoasunto.setText(tipoasunto1);
        txtasunto.setText(asunto1);
        txtestado.setText(estado1);
    }//GEN-LAST:event_formWindowActivated
public void recibeinfo(String folio,String nombre,String puesto,String area,String fecha,String horaes,String horall,String horas,String tipohorario,String tipoasunto,String asunto,String estado){
        
    folio1=folio;
    nombre1=nombre;
    puesto1=puesto;
    area1=area;
    fecha1=fecha;
    horaes1=horaes;
    horall1=horall;
    horas1=horas;
    tipohorario1=tipohorario;
    tipoasunto1=tipoasunto;
    asunto1=asunto;
    estado1=estado;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visSolicitudPase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visSolicitudPase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visSolicitudPase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visSolicitudPase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                visSolicitudPase dialog = new visSolicitudPase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAviso;
    public static javax.swing.JPanel pn_vissolipase;
    private javax.swing.JTextField txtarea;
    public static javax.swing.JTextArea txtasunto;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtfolio;
    private javax.swing.JTextField txthoraes;
    private javax.swing.JTextField txthorall;
    private javax.swing.JTextField txthoras;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpuesto;
    private javax.swing.JTextField txttipoasunto;
    private javax.swing.JTextField txttipohorario;
    // End of variables declaration//GEN-END:variables
}
