/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import Clases.Excel;
import Clases.ManagerUsers;
import Clases.ManagerInventarioGranel;
import Clases.ManagerComplemento;
import Clases.ManagerPermisos;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kevin
 */
public class Ventana_EstadisticaConsumible extends javax.swing.JDialog {
    ManagerInventarioGranel manager_inventario_granel;
    ManagerComplemento manager_complemento;
    ManagerPermisos manager_permisos;
    
    /**
     * Creates new form Ventana_asignar_EquipoComputo
     */
    public Ventana_EstadisticaConsumible(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Asignamos memoria al objeto
        manager_inventario_granel = new ManagerInventarioGranel();
        manager_complemento = new ManagerComplemento();
        manager_permisos = new ManagerPermisos();
        
        this.setTitle("Consulta de solicitudes Autorizadas o Canceladas.");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEstadistica = new javax.swing.JPopupMenu();
        ExcelConsumibles = new javax.swing.JMenuItem();
        pn_asignarEquipo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConsumibles = new JTable(){  public boolean isCellEditable(int rowIndex, int colIndex){  return false;  }  };
        btnBusquedaFecha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaIni = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        ExcelConsumibles.setText("Exportar a excel");
        ExcelConsumibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelConsumiblesActionPerformed(evt);
            }
        });
        MenuEstadistica.add(ExcelConsumibles);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_asignarEquipo.setLayout(null);

        tablaConsumibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Consumible", "Descripción", "Solicitado", "Entregado", "Existencias"
            }
        ));
        tablaConsumibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConsumiblesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaConsumiblesMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaConsumibles);

        pn_asignarEquipo.add(jScrollPane2);
        jScrollPane2.setBounds(10, 87, 979, 470);

        btnBusquedaFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBusquedaFecha.setText("Buscar por fecha");
        btnBusquedaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaFechaActionPerformed(evt);
            }
        });
        pn_asignarEquipo.add(btnBusquedaFecha);
        btnBusquedaFecha.setBounds(740, 30, 160, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha final:");
        pn_asignarEquipo.add(jLabel2);
        jLabel2.setBounds(490, 60, 80, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de incio:");
        pn_asignarEquipo.add(jLabel4);
        jLabel4.setBounds(460, 20, 100, 14);
        pn_asignarEquipo.add(fechaIni);
        fechaIni.setBounds(560, 10, 160, 30);
        pn_asignarEquipo.add(fechaFin);
        fechaFin.setBounds(560, 50, 160, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Seleccionar área:");
        pn_asignarEquipo.add(jLabel1);
        jLabel1.setBounds(10, 20, 110, 17);

        comboArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaActionPerformed(evt);
            }
        });
        pn_asignarEquipo.add(comboArea);
        comboArea.setBounds(120, 20, 290, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formularios.png"))); // NOI18N
        pn_asignarEquipo.add(jLabel3);
        jLabel3.setBounds(-16, -16, 1040, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_asignarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_asignarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        //ComboArea
        String lista = manager_complemento.obtenerAreas();
        String[] recoger = lista.split(",,");

        comboArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        comboArea.addItem("Todas");
        for(int i = 1; i <= recoger.length;i = i+2){
            comboArea.addItem(recoger[i]);
        }
    }//GEN-LAST:event_formWindowOpened
        
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void tablaConsumiblesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConsumiblesMouseReleased
        // TODO add your handling code here:
        if(SwingUtilities.isRightMouseButton(evt)){
            int r = tablaConsumibles.rowAtPoint(evt.getPoint());
            if (r >= 0 && r < tablaConsumibles.getRowCount())
            tablaConsumibles.setRowSelectionInterval(r, r);
            MenuEstadistica.show(evt.getComponent(), evt.getX(), evt.getY());//Mostramos el popMenu en la posición donde esta el cursor
        }//clic derecho
    }//GEN-LAST:event_tablaConsumiblesMouseReleased

    private void tablaConsumiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConsumiblesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaConsumiblesMouseClicked

    private void comboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaActionPerformed
        // TODO add your handling code here:
        if(manager_permisos.accesoModulo("consulta","Inventario",Principal.Username)){
            tablaConsumibles.setModel(manager_inventario_granel.estadisticasConsumiblesArea(comboArea.getSelectedItem().toString()));
        }else{
            JOptionPane.showMessageDialog(null, "Usted no cuenta con permisos para realizar consultas de estadísticas de consumibles.");
            tablaConsumibles.setModel(new DefaultTableModel());
        }
    }//GEN-LAST:event_comboAreaActionPerformed

    private boolean validarFecha(String fecha) {
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            formatoFecha.setLenient(false);
            formatoFecha.parse(fecha);
        } catch (ParseException e) {
            return false;
        }
        return true;
    }
    
    private void btnBusquedaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaFechaActionPerformed
        // TODO add your handling code here:
        if(manager_permisos.accesoModulo("consulta","Inventario",Principal.Username)){
            if(fechaIni.getDate() == null || fechaFin.getDate() == null){
                JOptionPane.showMessageDialog(null, "Ingrese el rango de tiempo por fechas");
            }else{
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                String fechaInicio = formato.format(fechaIni.getDate());
                if(validarFecha(fechaInicio)){
                    formato = new SimpleDateFormat("yyyy-MM-dd");
                    String fechaFinal = formato.format(fechaFin.getDate());
                    if(validarFecha(fechaFinal)){
                        tablaConsumibles.setModel(manager_inventario_granel.estadisticasConsumiblesFecha(comboArea.getSelectedItem().toString(),fechaInicio,fechaFinal));
                    }else{
                        JOptionPane.showMessageDialog(null, "El fomarto de fecha es incorrecto, tiene que ser yyyy-MM-dd");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El fomarto de fecha es incorrecto, tiene que ser yyyy-MM-dd");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Usted no cuenta con permisos para realizar consultas de estadísticas de consumibles.");
            tablaConsumibles.setModel(new DefaultTableModel());
        }
    }//GEN-LAST:event_btnBusquedaFechaActionPerformed

    private void ExcelConsumiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelConsumiblesActionPerformed
        // TODO add your handling code here:
        try{
            if(manager_permisos.accesoModulo("consulta","Inventario",Principal.Username)){
                Excel excel = new Excel();
                excel.GuardarComo(tablaConsumibles);
            }else{
                JOptionPane.showMessageDialog(null, "Usted no cuenta con permisos para realizar consultas en el inventario.");
            }
        }catch(NullPointerException e){

        }
    }//GEN-LAST:event_ExcelConsumiblesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana_EstadisticaConsumible dialog = new Ventana_EstadisticaConsumible(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExcelConsumibles;
    private javax.swing.JPopupMenu MenuEstadistica;
    private javax.swing.JButton btnBusquedaFecha;
    private javax.swing.JComboBox<String> comboArea;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pn_asignarEquipo;
    private javax.swing.JTable tablaConsumibles;
    // End of variables declaration//GEN-END:variables
}
