/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import Clases.ManagerUsers;
import Clases.ManagerSolicitud;
import Clases.ManagerPermisos;

import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kevin
 */
public class Ventana_ConsultaSolicitudes extends javax.swing.JDialog {
    ManagerSolicitud manager_solicitud;
    ManagerPermisos manager_permisos;
    
    /**
     * Creates new form Ventana_asignar_EquipoComputo
     */
    public Ventana_ConsultaSolicitudes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Asignamos memoria al objeto
        manager_solicitud = new ManagerSolicitud();
        manager_permisos = new ManagerPermisos();
        
        this.setTitle("Consulta de solicitudes Autorizadas o Canceladas.");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_asignarEquipo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDocumentos = new JTable(){  public boolean isCellEditable(int rowIndex, int colIndex){  return false;  }  };
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDocumentosProductos = new JTable(){  public boolean isCellEditable(int rowIndex, int colIndex){  return false;  }  };
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        comboEstatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_asignarEquipo.setLayout(null);

        tablaDocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Fecha de inicio", "Productos asignados", "No. Acta"
            }
        ));
        tablaDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDocumentosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaDocumentosMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDocumentos);

        pn_asignarEquipo.add(jScrollPane2);
        jScrollPane2.setBounds(10, 37, 979, 161);

        tablaDocumentosProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre Corto", "No. de serie", "Descripción", "Observaciones"
            }
        ));
        tablaDocumentosProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDocumentosProductosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaDocumentosProductos);

        pn_asignarEquipo.add(jScrollPane3);
        jScrollPane3.setBounds(10, 232, 979, 328);

        jLabel4.setText("Productos del documento");
        pn_asignarEquipo.add(jLabel4);
        jLabel4.setBounds(10, 212, 300, 14);
        pn_asignarEquipo.add(jSeparator2);
        jSeparator2.setBounds(10, 204, 979, 2);

        jLabel2.setText("Estatus:");
        pn_asignarEquipo.add(jLabel2);
        jLabel2.setBounds(628, 14, 40, 14);

        comboEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstatusActionPerformed(evt);
            }
        });
        pn_asignarEquipo.add(comboEstatus);
        comboEstatus.setBounds(672, 11, 320, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formularios.png"))); // NOI18N
        pn_asignarEquipo.add(jLabel3);
        jLabel3.setBounds(-6, -6, 1030, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_asignarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_asignarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        //COMBOESTATUS
        comboEstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        comboEstatus.addItem("Todos");
        comboEstatus.addItem("Autorizado");
        comboEstatus.addItem("Cancelado");
    }//GEN-LAST:event_formWindowOpened
        
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void tablaDocumentosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDocumentosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDocumentosMouseReleased

    private void tablaDocumentosProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDocumentosProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDocumentosProductosMouseClicked

    private void tablaDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDocumentosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            if(manager_permisos.accesoModulo("consulta","Solicitudes",Principal.Username)){
                int fila = tablaDocumentos.getSelectedRow();
                String id = tablaDocumentos.getValueAt(fila, 0).toString();

                //Llenamos la tabla de la relación documento-productos
                tablaDocumentosProductos.setModel(manager_solicitud.consumibles_SolicitudSalida(id));
            }else{
                JOptionPane.showMessageDialog(null, "Usted no cuenta con permisos para realizar consultas del historial de solicitudes.");
            }
        }//getClickCount
    }//GEN-LAST:event_tablaDocumentosMouseClicked

    private void comboEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstatusActionPerformed
        // TODO add your handling code here:
        if(manager_permisos.accesoModulo("consulta","Solicitudes",Principal.Username)){
            String estatus = comboEstatus.getSelectedItem().toString();

            //Llenamos la tabla de los documentos
            tablaDocumentos.setModel(manager_solicitud.tabla_SolicitudesEstatus(estatus));
        }else{
            JOptionPane.showMessageDialog(null, "Usted no cuenta con permisos para realizar consultas del historial de solicitudes.");
        }
    }//GEN-LAST:event_comboEstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana_ConsultaSolicitudes dialog = new Ventana_ConsultaSolicitudes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEstatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pn_asignarEquipo;
    private javax.swing.JTable tablaDocumentos;
    private javax.swing.JTable tablaDocumentosProductos;
    // End of variables declaration//GEN-END:variables
}
