/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JFrame;
import javax.swing.JTable;
import Clases.ManagerSolicitud;
import javax.swing.JOptionPane;
import Clases.validarCeldaNumero;
/**
 *
 * @author kevin
 */
public class Ventana_AceptaSalida extends javax.swing.JDialog {
    String id,user;
    ManagerSolicitud manager_solicitud;
    validarCeldaNumero validar;
    /**
     * Creates new form Ventana_solicitudSalida
     */
    public Ventana_AceptaSalida(java.awt.Frame parent, boolean modal,String id,String user) {
        super(parent, modal);
        initComponents();
        this.setTitle("Solicitud para salida de almacen-Especificar cantidad del producto solicitado");
        
        manager_solicitud = new ManagerSolicitud();
        validar = new validarCeldaNumero();
        this.id = id;
        this.user = user;
        tablaSolicitudSalida.setModel(manager_solicitud.tabla_SolicitudSalida(this.id));
        //tablaSolicitudSalida.setDefaultRenderer(Integer.class, validar);
        this.setLocationRelativeTo(null);
        
    }
    
    private Ventana_AceptaSalida(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudSalida = new JTable(){  
     public boolean isCellEditable(int rowIndex, int colIndex){  
         if(colIndex == 6){
             return true;
         } else{
             return false; 
         } 
     }  
 };
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        tablaSolicitudSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre corto", "Descripción", "Marca", "Solicitar"
            }
        ));
        tablaSolicitudSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaSolicitudSalidaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSolicitudSalida);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 718, 476);

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btnAceptar.setText(" Aceptar");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(236, 517, 120, 28);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btnCancelar.setText(" Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(362, 517, 120, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formularios.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 770, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validar(){
        boolean estado = true;
        try{
            //Revisamos todos los campos de la cantidad
            for(int i = 0; i<tablaSolicitudSalida.getRowCount();i++){
                if(Integer.parseInt(tablaSolicitudSalida.getValueAt(i, 6).toString()) < 0){
                    JOptionPane.showMessageDialog(null, "Por favor verifique los campos que estan en amarillo, se ingreso una cantidad menor a 1 en su solicitud.");
                    estado = false;
                    break;
                }//menor a 1
            }//for
            return estado;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor verifique el campo que esta en rojo, se ingresaron caracteres invalidos. Solo acepta numeros enteros mayores o iguales a 1.");
            return false;
        }
    }//validar
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        //Es necesario validar que los campos hayan sidoescritos unicamente con numeros (pendiente)
        if(validar()){
        
            //Obtenemos todas las cantidades de los productos
            int[] Cantidad = new int[tablaSolicitudSalida.getRowCount()];
            String[] Productos = new String[tablaSolicitudSalida.getRowCount()];
            for(int i = 0; i<Cantidad.length;i++){
                Cantidad[i] = Integer.parseInt(tablaSolicitudSalida.getValueAt(i, 6).toString());
                Productos[i] = tablaSolicitudSalida.getValueAt(i, 0).toString();
            }

            //Realizamos el registro
            if(manager_solicitud.registro_AceptaSalida(user,id,Productos, Cantidad)){
                JOptionPane.showMessageDialog(null, "Se atendio correctamente la solicitud de salida de almacen.");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo atender la solicitud de salida de almacen, verificar con el distribuidor.");
                this.dispose();
            }
            
        }//validar
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"Aceptar", "Cancelar"};
        int seleccion = JOptionPane.showOptionDialog(null, "¿Desea cancelar el proceso para atender la solicitud de salida de almacen?","Confirmación de cancelación", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if(seleccion == 0){
            this.dispose();
        }else{
        
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tablaSolicitudSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaSolicitudSalidaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(caracter != evt.getKeyChar()){
        
        }
        if(caracter < '0' || caracter > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_tablaSolicitudSalidaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana_AceptaSalida dialog = new Ventana_AceptaSalida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudSalida;
    // End of variables declaration//GEN-END:variables
}
